module.exports = [
    [
        'ArrayExpression',
        false,
        [ 'elements' ]
    ],
    [
        'AssignmentExpression',
        false,
        [
            'operator',
            'left',
            'right'
        ]
    ],
    [
        'BinaryExpression',
        false,
        [
            'operator',
            'left',
            'right'
        ]
    ],
    [
        'BlockStatement',
        true,
        [ 'body' ]
    ],
    [
        'BreakStatement',
        true,
        [ 'label' ]
    ],
    [
        'CallExpression',
        false,
        [
            'callee',
            'arguments'
        ]
    ],
    [
        'CatchClause',
        true,
        [
            'param',
            'body'
        ]
    ],
    [
        'ConditionalExpression',
        false,
        [
            'test',
            'consequent',
            'alternate'
        ]
    ],
    [
        'ContinueStatement',
        true,
        [ 'label' ]
    ],
    [
        'DebuggerStatement',
        true,
        []
    ],
    [
        'DoWhileStatement',
        true,
        [
            'body',
            'test'
        ]
    ],
    [
        'EmptyStatement',
        true,
        []
    ],
    [
        'ExpressionStatement',
        true,
        [ 'expression' ]
    ],
    [
        'ForInStatement',
        true,
        [
            'left',
            'right',
            'body'
        ]
    ],
    [
        'ForStatement',
        true,
        [
            'init',
            'test',
            'update',
            'body'
        ]
    ],
    [
        'FunctionDeclaration',
        true,
        [
            'id',
            'params',
            'body'
        ]
    ],
    [
        'FunctionExpression',
        false,
        [
            'id',
            'params',
            'body'
        ]
    ],
    [
        'GenSym',
        false,
        [
            'ns',
            'uniqueId'
        ]
    ],
    [
        'Identifier',
        false,
        [ 'name' ]
    ],
    [
        'IfStatement',
        true,
        [
            'test',
            'consequent',
            'alternate'
        ]
    ],
    [
        'LabeledStatement',
        true,
        [
            'label',
            'body'
        ]
    ],
    [
        'Literal',
        false,
        [ 'value' ]
    ],
    [
        'LogicalExpression',
        false,
        [
            'operator',
            'left',
            'right'
        ]
    ],
    [
        'MemberExpression',
        false,
        [
            'computed',
            'object',
            'property'
        ]
    ],
    [
        'NewExpression',
        false,
        [
            'callee',
            'arguments'
        ]
    ],
    [
        'ObjectExpression',
        false,
        [ 'properties' ]
    ],
    [
        'Program',
        true,
        [ 'body' ]
    ],
    [
        'Property',
        true,
        [
            'key',
            'value'
        ]
    ],
    [
        'ReturnStatement',
        true,
        [ 'argument' ]
    ],
    [
        'SequenceExpression',
        false,
        [ 'expressions' ]
    ],
    [
        'SwitchCase',
        true,
        [
            'test',
            'consequent'
        ]
    ],
    [
        'SwitchStatement',
        true,
        [
            'discriminant',
            'cases'
        ]
    ],
    [
        'ThisExpression',
        false,
        []
    ],
    [
        'ThrowStatement',
        true,
        [ 'argument' ]
    ],
    [
        'TryStatement',
        true,
        [
            'block',
            'handlers',
            'finalizer'
        ]
    ],
    [
        'UnaryExpression',
        false,
        [
            'operator',
            'argument'
        ]
    ],
    [
        'UpdateExpression',
        false,
        [
            'operator',
            'prefix',
            'argument'
        ]
    ],
    [
        'VariableDeclaration',
        true,
        [
            'kind',
            'declarations'
        ]
    ],
    [
        'VariableDeclarator',
        true,
        [
            'id',
            'init'
        ]
    ],
    [
        'WhileStatement',
        true,
        [
            'test',
            'body'
        ]
    ],
    [
        'WithStatement',
        true,
        [
            'object',
            'body'
        ]
    ]
];
